spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.subbu.estore: INFO
#    org.hibernate.type: TRACE

server:
  port: 8083