spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379

logging:
  level:
    com.subbu.estore: INFO
#    org.hibernate.type: TRACE

server:
  port: 8081